### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [acenelio/workshop-springboot2-mongodb#6]
Professro estou trabalhando em um projeto pessoal: https://github.com/DevJoseWeb/SistemaDeClassificaoAspinwall
 ele funciona local perfeitamente, mas quando eu rodo na AWS ele da problema de Data. Estou usando seu projeto como base. Ja passou por isso ?
Ja tentei de tudo:
 /*@Temporal(TemporalType.DATE)
    @JsonFormat(shape = JsonFormat.Shape.STRING,
            pattern = "dd/MM/yyyy",
            locale = "pt-BR",
            timezone = "Brazil/East")
    @JsonDeserialize(using = JsonDateDeserializer.class)
    @JsonSerialize(using = JsonDateSerializer.class)
    @JsonFormat(pattern="dd/MM/yyyy HH:mm:ss")*/
    public Date datacadastro;

 : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.util.Date] for value ''; nested exception is java.lang.IllegalArgumentException] with root cause

java.lang.IllegalArgumentException: null
	at java.base/java.util.Date.parse(Date.java:616) ~[na:na]
	at java.base/java.util.Date.<init>(Date.java:274) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]

**Comment by adormundo** [comment]
Pra quem fez a instalação padrão do MongoDB e não sabe conectar no **MongoDB Compass**, basta inserir 

`mongodb://localhost:27017` e conectar

![image](https://user-images.githubusercontent.com/26398066/159191351-87bac767-fd19-424b-b67a-8dea1bfa2ec6.png)

Você pode verificar o IP e a Porta também na execução do MongoDB
![image](https://user-images.githubusercontent.com/26398066/159191599-2cc9ac6d-7f6a-47ac-a7e9-7c85f36fe547.png)
